
import React from 'react';
import { geminiService } from '../services/geminiService';
import { Sparkles, Loader2, MousePointer2 } from 'lucide-react';

const CatHero: React.FC = () => {
  const [imgUrl, setImgUrl] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(false);

  const fetchCat = async () => {
    setLoading(true);
    const url = await geminiService.generateCatArt();
    if (url) setImgUrl(url);
    setLoading(false);
  };

  React.useEffect(() => {
    fetchCat();
  }, []);

  return (
    <div className="relative group mb-12 overflow-hidden border border-gray-100 bg-white aspect-square max-w-[300px] mx-auto lg:mx-0">
      {loading ? (
        <div className="absolute inset-0 flex flex-col items-center justify-center space-y-3 bg-white">
          <Loader2 className="animate-spin text-gray-200" size={32} />
          <span className="text-[10px] uppercase tracking-widest text-gray-400">Summoning a Feline...</span>
        </div>
      ) : (
        <img 
          src={imgUrl || 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=500&auto=format&fit=crop'} 
          alt="AI Cat Art" 
          className="w-full h-full object-cover grayscale transition-all duration-700 group-hover:scale-105"
        />
      )}
      
      <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
        <button 
          onClick={fetchCat}
          disabled={loading}
          className="bg-white text-black px-4 py-2 text-[10px] font-bold uppercase tracking-widest flex items-center space-x-2 hover:bg-black hover:text-white transition-all transform translate-y-4 group-hover:translate-y-0"
        >
          <MousePointer2 size={12} />
          <span>Pet for new Art</span>
        </button>
      </div>

      <div className="absolute bottom-2 left-2 flex items-center space-x-1 opacity-50">
         <Sparkles size={8} className="text-black" />
         <span className="text-[8px] uppercase tracking-tighter font-bold">Generated by Gemini</span>
      </div>
    </div>
  );
};

export default CatHero;
